alias wget='wget --no-check-certificate'
alias curl='curl --insecure'
alias ls='eza --group-directories-first --icons --git'
alias ll='ls -lhG'
alias la='ls -lahG'
alias tree='eza --git-ignore -lT'
alias bat='bat --theme="ansi"'
alias cat='bat -pp'
alias less='bat -p --paging always'
alias grep='grep --color=auto'
alias cp='cp -i'
alias mv='mv -i'
alias df='duf'

alias vim='env NVIM_APPNAME=nvim-main nvim'
alias res='source ~/.zshrc'
alias g='gitui'
alias gitc='git clone'
alias gitd='git difftool --no-symlinks --dir-diff'
alias pip='python -m pip'
alias view="kitty +kitten icat"
alias ff='fastfetch'
alias onefetch='onefetch --no-color-palette --include-hidden'
alias yt='yt-dlp --proxy "https://127.0.0.1:9910" -c -N 16'
alias bili='bilix v -oa'
alias nvimprof='env NVIM_APPNAME=nvim-main vim-startuptime -count 128 -warmup 2 -vimpath nvim | head -n20'
