# Settings
workspace_limit	= 8
focus_close		= previous
focus_default		= last

# Window Decoration
border_width		= 5
color_focus		= rgb:5e/81/ac
color_focus_maximized	= rgb:5e/81/ac
color_unfocus		= rgb:88/88/88
color_unfocus_maximized	= rgb:88/88/00
region_padding		= 5
tile_gap		= 5

# Bar settings
bar_action		= ~/.config/spectrwm/baractions.sh
bar_action_expand	= 1
maximize_hide_bar	= 1
bar_border_width	= 0
bar_color		= rgb:15/4c/79
bar_font		= CaskaydiaCove NF Mono:pixelsize=20:antialias=true
bar_font_color		= rgb:81/c0/e1,white
bar_format		= +|1L+@fg=1;+@bg=0;Workspace +I  +@fg=0;+C: +W +|2R+A
bar_justify		= center
workspace_indicator	= listall

# Dialog box size ratio when using TRANSSZ quirk; 0.3 < dialog_ratio <= 1.0
dialog_ratio		= 0.6

# Launch applications in a workspace of choice
autorun			= ws[1]:picom -cf
autorun			= ws[1]:touchegg --daemon
autorun			= ws[1]:touchegg
autorun			= ws[1]:skippy-xd --start-daemon
autorun 		= ws[1]:nitrogen --restore
autorun			= ws[1]:/usr/libexec/polkit-gnome-authentication-agent-1
autorun			= ws[1]:dunst

# Keybindings
modkey = Mod1

# Some important default keybinds
# M-⟨Space⟩           cycle_layout
# M-j, M-⟨TAB⟩        focus_next
# M-k, M-S-⟨TAB⟩      focus_prev
# M-b                 bar_toggle
# M-⟨1-9,0,F1-F12⟩    ws_⟨1-22⟩
# M-S-⟨1-9,0,F1-F12⟩  mvws_⟨1-22⟩
# M-S-⟨Delete⟩        lock
# M-h                 master_shrink (which just resizes width)
# M-l                 master_grow
# M-[                 move_left
# M-]                 move_right
# M-S-[               move_up
# M-S-]               move_down
# M-/                 search_workspace (more like search window)

# Defining programs
program[lock]		= xfce4-screensaver-command -lock
program[rofi-quit]	= rofi -show power-menu -modi power-menu:~/.local/bin/rofi-power-menu
program[term]		= kitty
program[firefox]	= firefox 
program[menu]		= rofi -show drun
program[flameshot]	= flameshot gui
program[search]		= rofi -show window
program[caja]		= caja
program[skippy-xd]	= skippy-xd
program[volume]		= pavucontrol

# Program keybindings
bind[]			= MOD+p			# disable dmenu
bind[]          	= MOD+Shift+q   # disable default quit keybinding
bind[term]		= MOD+Return
bind[firefox]		= MOD+Shift+f
bind[menu]		= MOD+Shift+d
bind[flameshot]		= MOD+Shift+p
bind[caja]		= MOD+e
bind[skippy-xd]		= MOD+Tab
bind[volume]		= MOD+Shift+v
bind[rofi-quit]		= MOD+Shift+x

# Window actions
bind[wind_kill]		= MOD+q
bind[restart]		= MOD+Shift+r
bind[layout_max]	= MOD+Shift+m
bind[ws_next_move]	= MOD+Shift+l
bind[ws_prev_move]	= MOD+Shift+h
bind[maximize_toggle]	= MOD+Shift+m
bind[fullscreen_toggle]	= MOD+F11
bind[swap_main]		= MOD+Shift+Return
bind[ws_prev]	= MOD+Shift+k
bind[ws_next]	= MOD+Shift+j

# Quirks
quirk[Gephgui-wry:gephgui-wry] = FLOAT + ANYWHERE + WS[1]
quirk[Watt Toolkit x64 v2.8.4 Î² for Linux] = FLOAT + ANYWHERE + WS[1]
