#! /bin/bash

export SCRIPTPATH="$(cd "$(dirname "$0")" ; pwd -P)"
# clean cache from last run
if [ -f "/tmp/leftwm-theme-down" ]; then
   /tmp/leftwm-theme-down
  rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

leftwm command "LoadTheme ~/.config/leftwm/themes/current/theme.toml" &
feh --bg-scale $SCRIPTPATH/bg.jpg &
picom -cf &
cp -f $SCRIPTPATH/alacritty.yml ~/.config/alacritty/ &
cp -f $SCRIPTPATH/gruvbox-dark-soft.rasi ~/.config/rofi/ &
conky -c $SCRIPTPATH/clock.conf
